"""add role to accounts

Revision ID: 58f56c7bbbba
Revises: a0ccb5ace260
Create Date: 2025-04-04 00:16:44.059906

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "58f56c7bbbba"
down_revision: Union[str, None] = "a0ccb5ace260"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
